name: Java com Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Instalando JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compliando pacotes Maven
        run: mvn -B clean package -DskipTests
      - name: Verificando testes unitários Maven
        run: mvn -B clean verify